### ISSUE TITLE
Something Error in prediction

### ISSUE THREAD

**Issue by susutBu** [ambarishbiswas/CRISPRDetect_3.0#1]
Hey Biswas:
Thanks for great effort  of CRISPRDetect3! But something wrong when I runs CRISPRDetect3 with default paramaeter on NZ_CP006019.gbk file. The following is the description of Error log:

`Error: File size= The GBK file NZ_CP006019.gbk does not contain any genomic sequence. Please download a full .gbk file
NA,Palaeococcus pacificus DY20341, complete genome.,Archaea
        Putative CRISPRs prediction done.
        Total putative CRISPRs to process: 0 from 0 sequences
`
How can I solve it.
Looking forward your reply. Thanks

**Comment by susutBu** [comment]
When I run following command, it worked !
`CRISPRDetect3 -f test_multifasta.fa -o test_CRISPRDetect3 -check_direction 0 -array_quality_score_cutoff 3 -T 0 > test.log
`

**Comment by ambarishbiswas** [comment]
The GBK file doesn't contain any sequences. When you obtain GBK file from NCBI, select "GenBank full". That should work.

**Comment by susutBu** [comment]
> The GBK file doesn't contain any sequences. When you obtain GBK file from NCBI, select "GenBank full". That should work.

Unfortunately, it not worked.
[NZ_CP006019.ZIP](https://github.com/ambarishbiswas/CRISPRDetect_3.0/files/6928526/NZ_CP006019.ZIP)

**Comment by ambarishbiswas** [comment]
Hi, can you check if "seqret" is installed and in path?

**Comment by susutBu** [comment]
> Hi, can you check if "seqret" is installed and in path?

Oh, it worked! Thanks a lot. I think I just copy the relative software fromm 2.2, but I forgot the relative lib file of seqret.

**Comment by ambarishbiswas** [comment]
Glad to know it worked :-)
